### ISSUE TITLE
cfa (take 2)

### ISSUE THREAD

**Issue by jgravois** [jgravois/presentations#14]
my slides from last time can be found here:
https://johngravois.com/presentations/cfora-esri/

not sure if you remember it or not @hamhands, but if you do and you have any critical feedback, it would be **_extremely**_ helpful.

this is the copy that was sent to Fellows, technical staff and nearby Brigade captains to announce my visit on Tuesday 8/23.

> Hi, Team!
> 
> Esri has been a consistent supporter of CfA since its inception. Founded in 1969, the geospatial company’s software is the de facto standard for digital spatial asset management and analysis in government agencies of all sizes.  As part of our partnership this year, John Gravois, a longtime Developer Advocate at Esri, is coming to speak to us. 
> 
> John is part geographer, part web developer and knowledgeable on Esri’s desktop tools, on premise server software and SAS offerings. He'll be talking about:
> - Giving a spatial context to projects that are not map centric
> - How to speed up development/prototyping when working with live government services
> - Getting GeoJSON out of Esri software
> - Displaying content in popular OSS APIs like Leaflet (without ETL)
> - Esri’s history, trajectory, and the role of Open Source
> 
> Afterwards, he'll stick around to chat with technical staff, brigade members and fellows if you’d like to get down to brass tacks and discuss individual projects and/or how to get the most of Esri's software donations.

**Comment by jgravois** [comment]
realized thats pretty vague.  more specifically, did I:
- stick my foot in my mouth?
- belabor any unnecessary/irrelevant/boring topics?
- skip something compelling?
- miss an opportunity that other guests took better advantage of?

part of me feels like i should be really candid about the fact that many of those folks don't give Esri a fair shake and that many partner cities leave disappointed that CfA solutions don't integrate with back office software.  

but even if there's truth in that, i don't want to come off as aggressive or antagonistic.

**Comment by hamhands** [comment]
My biggest takeaway from the talk last year was that my project wasn't really spatial so why would I need to use esri's stuff. If you can make the case that 1) there is a ton of rad + underutilizied spatial data that the cities fellows work in are already actively maintaining and 2) that esri makes it easy to do sweet stuff with that data (preferably client-side) then I think you'll win a lot of the room over. I think you do the second thing, but not so much the first.

A quick note re strategy: for the fellows, I doubt you're going to see much adoption this late in the year. Most of the teams are (or should be) in the process of handing their projects off to their city partners. They won't likely be into adding new features or adopting a whole new stack. For this reason it might be worth doing a little digging as to the [project focus areas](https://www.codeforamerica.org/what) (safety & justice likely a good fit) and maybe build an example around one or two. 

Two pedantic things: 1) I'd stick with calling it CfA rather than C for A and 2) maybe don't say it's not a salespitch. Whenever someone tells me what they're presenting isn't a salespitch I become instantly suspicious that they're trying to sell me something :)

**Comment by hamhands** [comment]
I think if you make the point that our technology is more than just desktop map creation but an active community of data stewards within city government who spin up data services that civic hackers can build sustainable solutions on top off then I think you'll have a better chance of winning them over.

**Comment by jgravois** [comment]
> 1) I'd stick with calling it CfA

👍  i definitely noticed that my url/title from last go round were a bit tone deaf when i copy/pasted the link a few minutes ago.

**Comment by jgravois** [comment]
these are some takeways i am shooting for:
- Esri tech is more than just desktop map creation, its an active community of data stewards within city government who spin up services
- using location is a great way to filter the firehouse, map or no map
- utilization of spatial datasets is what brings value to a GIS
- building solutions on top of live services is more sustainable than ETL.
- its easier than ever,  both for cities and independent devs, to get a hold of tools and share work on the web
- back office plumbing / tech janitorial work is _sorely_ needed, but not glamorous enough for press releases
- Esri wants critical feedback from CfA fellows regarding what should come next

@migurski, do you have any advice to share?
either way, if you're in the **C**ity next week we should go for a pedal!

**Comment by migurski** [comment]
All of this sounds good! I agree with @hamhands comments. Esri is in the interesting position of being the one true game in town for much of this stuff; for OpenAddresses project we spend a tremendous amount of our energy keeping up with Arcserver instances around the world. 

I’m around next week, would love to meet up!
