### ISSUE TITLE
dev summit 2017 post mortem

### ISSUE THREAD

**Issue by jgravois** [jgravois/presentations#20]
we both received quite a bit of enthusiastic feedback from JS and GitHub _for Geographers_.

### JS

demo theater was near overflowing (~120 folks?)

* we should trim about 15 minutes of material from the talk.
* john definitely spent too much time discussing operators.  much of the information could have been introduced within the context of functions
* i felt that pat provided a little too much depth regarding closures and deconstructing the event loop.  we could have gotten away with something slightly higher level.

when i first got familiar with JS (using APIs) i wasn't writing my own custom classes and digging in deeply to `this` until _after_ i overcame more simple gotchas like having named variables be unexpectedly entirely undefined.

for example, talking about why AMD modules make it necessary to wire up DOM event listeners like button click handlers _within_ the callback (as opposed to directly within HTML) would probably be a sufficient introduction to the concept of 'scope'.

### GitHub

room was completely full (~80 folks?)

the talk went smoothly.  it probably would have made sense to organize the demo so that we used increasingly advanced tools. ie:

1. first edit directly on GitHub
2. then clone locally and use a UI like GitKraken
3. then use git commands to resolve a merge conflict.

that said, folks didn't seem to mind.

i spoke to Jim and he reminded me that the deadline to submit talks for UC has already passed, but i still like the idea of making this a perennial talk series.

cc/ @patrickarlt

**Comment by patrickarlt** [comment]
Agree with everything above. Some ideas below:

### General

Demo theater sized rooms seem to be about the right size for these. Bigger then the smaller room sizes but larger then the large ballrooms. Maybe ~100 people per talk.

### JS

Demo theater was ~~near~~ overflowing.

@jgravois from your above comments we could do this demo to replace the scope/closures stuff:

```js
// variables declared inside functions cant be accessed outside functions this is called "lexical scope" or more simply "scope"

// since these are declared outside the callback to `require` we can access them in the global scope.
var map;
var mapView;

require([
  "esri/Map",
  "esri/MapView"
], function (Map, MapView) {
  // instead of declaring the variables here we just assign values to them.
  map = new Map({ ... });
  mapView = new Map({ ... });
});

// now we can access `map` and `mapView` in the console.
```

Event loop stuff can all go talking about how JavaScript is async is enough. I still think talking about `this` is super important since it is a big gotcha. I would also cut out everything I skipped over about NPM and the ecosystem.

I also think we need to play up the links to the GIS stuff (you were good at that) since it is REALLY relatable.

### Git/GitHub

I like this format and the length was good. Next year we should look into the multiplexing feature of Reveal to keep slides in sync across our machines. The ordering of the tools didn't seem to matter that much but if you want to rearrange the workflow from simple to complex for next year i wont argue.

I **WOULD** however put a "Installing and using Git" slide before the first command line demo just to talk about about installing Git and the various terminals that are available.

Given that so many people use Windows I'm also wondering if we should get a Windows machine to run the session on? I know enough Powershell to do it and it would be more relevant.

### CSS

The CSS talks were less crowded last year but that might just be because the large ballrooms are the wrong size for these talks. I only had about 20-30 people in a huge ballroom on Friday, So I kind of question the value of repeat sessions now.

I think I've got this one pretty dialed in after this year. I can run it right at 45 minutes and the slides and demos are solid. The only thing I might do next year is tweak the demos and links and talk about CSS Grid if it gets more browser support.

### Next Year

I would really like to get these talks off the Dev-to-Dev track and make room for more experimental stuff. Maybe we can move the JS and CSS to the JavaScript track. Apparently people were giving good feedback about these talks at the JavaScript island.

I think we rerun all 3 of these next year and also try them at UC (2018 since we missed the 2017 boat) since we got good feedback on all them and have some solid improvements we can make. I would be fine with repeating stuff Friday but we should try for smaller rooms on Friday.

I also got multiple comments about running these earlier in the week to help set the context for more advanced sessions which is hard but probably worth doing.

Lots of people wanted to see more of the "for Geographers" concept but no one could nail down anything specific that they wanted to hear a talk on.  That said I gave [Design & UX Tips for Maps](http://patrickarlt.com/dev-summit-talk-design-concepts/#/) to a packed house in a 2014 demo theater so I could resurrect that for next year.

Lastly, I had someone who attended all 3 "for Geographers" sessions float the idea of doing a 1 day pre-conference workshop of all these sessions bundled together plus a bunch of other stuff. If we do a "Web Design and UX for Geographers" we already have 4 hours of content so doesn't seem totally crazy. I asked the guy if he would pay $200 for it and he was really enthusiastic. This would be ton of work but could really pay off. If we could find more people to run more sections maybe we could pull off something ambitious.

**Comment by jgravois** [comment]
well put. as usual.
